# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('college', models.CharField(default=b'', max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('phone_one', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'user_profile',
            },
        ),
    ]
