# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, default=b'', max_length=1000)),
                ('query_type', models.CharField(max_length=50)),
                ('option1', models.CharField(blank=True, max_length=1000)),
                ('option2', models.CharField(blank=True, max_length=1000)),
                ('option3', models.CharField(blank=True, max_length=1000)),
                ('option4', models.CharField(blank=True, max_length=1000)),
                ('option6', models.CharField(blank=True, max_length=1000)),
                ('option7', models.CharField(blank=True, max_length=1000)),
                ('option8', models.CharField(blank=True, max_length=1000)),
                ('option9', models.CharField(blank=True, max_length=1000)),
                ('option10', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='user_profile',
            name='questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
