# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20160405_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='phone_one',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='questions',
        ),
    ]
