# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20160412_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='coach',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.coach_profile'),
        ),
    ]
