# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_user_profile_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'pictures'),
        ),
    ]
