# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20160413_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'pictures/default.jpg', null=True, upload_to=b'pictures'),
        ),
    ]
