# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20160414_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'pictures/default.jpg', null=True, upload_to=b'pictures'),
        ),
        migrations.AddField(
            model_name='coach_profile',
            name='about_me',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='coach_profile',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coach_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=b'pictures/default.jpg', null=True, upload_to=b'pictures'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
