# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20160414_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='coach_profile',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
