# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20160414_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='coach_profile',
            name='phone_one',
            field=models.BigIntegerField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(default=b'', max_length=20, null=True),
        ),
    ]
